version: "2"
linters:
  enable:
    - errorlint
  settings:
    errorlint:
      errorf: true
      asserts: true
      comparison: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
